@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant ":DeleteDoctorCommandParser" as DeleteDoctorCommandParser LOGIC_COLOR
participant "d:DeleteDoctorCommand" as DeleteDoctorCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete_d 1")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("delete_d 1")
activate MediConnectParser

create DeleteDoctorCommandParser
MediConnectParser -> DeleteDoctorCommandParser
activate DeleteDoctorCommandParser

DeleteDoctorCommandParser --> MediConnectParser
deactivate DeleteDoctorCommandParser

MediConnectParser -> DeleteDoctorCommandParser : parse("1")
activate DeleteDoctorCommandParser

create DeleteDoctorCommand
DeleteDoctorCommandParser -> DeleteDoctorCommand
activate DeleteDoctorCommand

DeleteDoctorCommand --> DeleteDoctorCommandParser : d
deactivate DeleteDoctorCommand

DeleteDoctorCommandParser --> MediConnectParser : d
deactivate DeleteDoctorCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteDoctorCommandParser -[hidden]-> MediConnectParser
destroy DeleteDoctorCommandParser

MediConnectParser --> LogicManager : d
deactivate MediConnectParser

LogicManager -> DeleteDoctorCommand : execute()
activate DeleteDoctorCommand

DeleteDoctorCommand -> Model : deleteDoctor(1)
activate Model

Model --> DeleteDoctorCommand
deactivate Model

create CommandResult
DeleteDoctorCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteDoctorCommand
deactivate CommandResult

DeleteDoctorCommand --> LogicManager : result
deactivate DeleteDoctorCommand

[<--LogicManager
deactivate LogicManager
@enduml