@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant ":DeletePatientCommandParser" as DeletePatientCommandParser LOGIC_COLOR
participant "d:DeletePatientCommand" as DeletePatientCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete_p 1")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("delete_p 1")
activate MediConnectParser

create DeletePatientCommandParser
MediConnectParser -> DeletePatientCommandParser
activate DeletePatientCommandParser

DeletePatientCommandParser --> MediConnectParser
deactivate DeletePatientCommandParser

MediConnectParser -> DeletePatientCommandParser : parse("1")
activate DeletePatientCommandParser

create DeletePatientCommand
DeletePatientCommandParser -> DeletePatientCommand
activate DeletePatientCommand

DeletePatientCommand --> DeletePatientCommandParser : d
deactivate DeletePatientCommand

DeletePatientCommandParser--> MediConnectParser : d
deactivate DeletePatientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeletePatientCommandParser -[hidden]-> MediConnectParser
destroy DeletePatientCommandParser

MediConnectParser --> LogicManager : d
deactivate MediConnectParser

LogicManager -> DeletePatientCommand : execute()
activate DeletePatientCommand

DeletePatientCommand -> Model : deletePatient(1)
activate Model

Model --> DeletePatientCommand
deactivate Model

create CommandResult
DeletePatientCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePatientCommand : result
deactivate CommandResult

DeletePatientCommand --> LogicManager : result
deactivate DeletePatientCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
