@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class "UniqueItemList" as UniquePersonList
class "UniqueItemList" as UniqueTagList
class "{abstract}\nData" as Data

Database *-right-> "1" UniquePersonList
Database *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Data

Data -up-> "*" Tag

Data *--> Remark
@enduml
