@startuml
!include ./style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant ":EditDoctorCommandParser" as EditDoctorCommandParser LOGIC_COLOR
participant "e:EditDoctorCommand" as EditDoctorCommand LOGIC_COLOR
participant "c:CommandResult" as CommandResult LOGIC_COLOR
participant "d:EditDoctorDescriptor" as EditDoctorDescriptor LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit_d 5 ic\T0123456B")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("edit_d 5 ic\T0123456B")
activate MediConnectParser

create EditDoctorCommandParser
MediConnectParser -> EditDoctorCommandParser
activate EditDoctorCommandParser

EditDoctorCommandParser --> MediConnectParser
deactivate EditDoctorCommandParser

MediConnectParser -> EditDoctorCommandParser : parse("edit_d 5 ic\T0123456B")
activate EditDoctorCommandParser

create EditDoctorDescriptor
EditDoctorCommandParser -> EditDoctorDescriptor
activate EditDoctorDescriptor

EditDoctorDescriptor --> EditDoctorCommandParser : d
deactivate EditDoctorDescriptor

create EditDoctorCommand
EditDoctorCommandParser -> EditDoctorCommand : EditDoctorCommand(5, d)
activate EditDoctorCommand

EditDoctorCommand --> EditDoctorCommandParser : e
deactivate EditDoctorCommand

EditDoctorCommandParser --> MediConnectParser : e
deactivate EditDoctorCommandParser

EditDoctorCommandParser -[hidden]-> MediConnectParser
destroy EditDoctorCommandParser

MediConnectParser --> LogicManager : e
deactivate MediConnectParser

LogicManager -> EditDoctorCommand : execute()
activate EditDoctorCommand

EditDoctorCommand -> EditDoctorCommand : createEditedDoctor(5, d)
activate EditDoctorCommand

EditDoctorCommand --> EditDoctorCommand : editedDoctor
deactivate EditDoctorCommand

EditDoctorCommand -> Model : setDoctor(5, editedDoctor)
activate Model

Model --> EditDoctorCommand
deactivate Model

create CommandResult
EditDoctorCommand -> CommandResult
activate CommandResult

CommandResult --> EditDoctorCommand : c
deactivate CommandResult

EditDoctorCommand --> LogicManager : c
deactivate EditDoctorCommand
@enduml
