@startuml
!include ./style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant ":AppointmentRemarkCommandParser" as AppointmentRemarkCommandParser LOGIC_COLOR
participant "a:AppointmentRemarkCommand" as AppointmentRemarkCommand LOGIC_COLOR
participant "c:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("remark_a 2 r\\follow up required")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("remark_a 2 r\\follow up required")
activate MediConnectParser

create AppointmentRemarkCommandParser
MediConnectParser -> AppointmentRemarkCommandParser
activate AppointmentRemarkCommandParser

AppointmentRemarkCommandParser --> MediConnectParser
deactivate AppointmentRemarkCommandParser

MediConnectParser -> AppointmentRemarkCommandParser : parse("2 r\\follow up required"")
activate AppointmentRemarkCommandParser

create AppointmentRemarkCommand
AppointmentRemarkCommandParser -> AppointmentRemarkCommand : AppointmentRemarkCommand(2, "follow up required")
activate AppointmentRemarkCommand

AppointmentRemarkCommand --> AppointmentRemarkCommandParser : a
deactivate AppointmentRemarkCommand

AppointmentRemarkCommandParser --> MediConnectParser : a
deactivate AppointmentRemarkCommandParser

AppointmentRemarkCommandParser -[hidden]-> MediConnectParser
destroy AppointmentRemarkCommandParser

MediConnectParser --> LogicManager : a
deactivate MediConnectParser

LogicManager -> AppointmentRemarkCommand : execute()
activate AppointmentRemarkCommand

AppointmentRemarkCommand -> Model : setAppointment(appointmentToEdit, editedAppointment)
activate Model

Model --> AppointmentRemarkCommand
deactivate Model

AppointmentRemarkCommand -> Model : updateFilteredAppointmentList(PREDICATE_SHOW_ALL_APPOINTMENTS)
activate Model

Model --> AppointmentRemarkCommand
deactivate Model

create CommandResult
AppointmentRemarkCommand -> CommandResult
activate CommandResult

CommandResult --> AppointmentRemarkCommand : c
deactivate CommandResult

AppointmentRemarkCommand --> LogicManager : c
deactivate AppointmentRemarkCommand
@enduml
