@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters EditXYZCommand with a specified index and parameter;
floating note right
    XYZ = Appointment, Doctor or Patient
end note
:MediConnectParser parses the command;
:EditXYZCommandParser parses the arguments provided;
if () then ([command is valid])
  :New EditXYZCommand instance is created;
  if () then ([XYZ object already exists])
    :Outputs error message;
  else ([XYZ object does not exist])
  :FilteredXYZList is updated with the new XYZ item;
  endif
else ([command is invalid])
  :Outputs error message;
endif
stop

@enduml
