@startuml
!include style.puml
skinparam ArrowFontStyle plain

box NewLogic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant ":FindPatientCommandParser" as FindPatientCommandParser LOGIC_COLOR
participant "p:FindPatient" as FindPatient LOGIC_COLOR
participant ":NameContainsKeywordsPatientPredicate" as NameContainsKeywordsPatientPredicate LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find_p John")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("find_p John")
activate MediConnectParser

create FindPatientCommandParser
MediConnectParser -> FindPatientCommandParser
activate FindPatientCommandParser


FindPatientCommandParser --> MediConnectParser
deactivate FindPatientCommandParser

MediConnectParser -> FindPatientCommandParser : parse("John")
activate FindPatientCommandParser

create FindPatient
FindPatientCommandParser -> FindPatient :
activate FindPatient

create NameContainsKeywordsPatientPredicate
FindPatient -> NameContainsKeywordsPatientPredicate : NameContainsKeywordsPatientPredicate([John])
activate NameContainsKeywordsPatientPredicate
NameContainsKeywordsPatientPredicate --> FindPatient : predicate
deactivate NameContainsKeywordsPatientPredicate


FindPatient --> FindPatientCommandParser : p
deactivate FindPatient

FindPatientCommandParser --> MediConnectParser : p
deactivate FindPatientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindPatientCommandParser -[hidden]-> MediConnectParser
destroy FindPatientCommandParser

MediConnectParser --> LogicManager : p
deactivate MediConnectParser

LogicManager -> FindPatient : execute()
activate FindPatient

FindPatient -> Model : getFilteredPatientList(predicate)
activate Model

Model --> FindPatient
deactivate Model

create CommandResult
FindPatient -> CommandResult
activate CommandResult

CommandResult --> FindPatient
deactivate CommandResult

FindPatient --> LogicManager : result
deactivate FindPatient

[<--LogicManager
deactivate LogicManager
@enduml
