@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant ":FindDoctorCommandParser" as FindDoctorCommandParser LOGIC_COLOR
participant "d:FindDoctorCommand" as FindDoctorCommand LOGIC_COLOR
participant ":NameContainsKeywordsDoctorPredicate" as NameContainsKeywordsDoctorPredicate LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find_d John")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("find_d John")
activate MediConnectParser

create FindDoctorCommandParser
MediConnectParser -> FindDoctorCommandParser
activate FindDoctorCommandParser


FindDoctorCommandParser --> MediConnectParser
deactivate FindDoctorCommandParser

MediConnectParser -> FindDoctorCommandParser : parse("John")
activate FindDoctorCommandParser

create FindDoctorCommand
FindDoctorCommandParser -> FindDoctorCommand :
activate FindDoctorCommand

create NameContainsKeywordsDoctorPredicate
FindDoctorCommand -> NameContainsKeywordsDoctorPredicate
activate NameContainsKeywordsDoctorPredicate
NameContainsKeywordsDoctorPredicate --> FindDoctorCommand : predicate
deactivate NameContainsKeywordsDoctorPredicate


FindDoctorCommand --> FindDoctorCommandParser : d
deactivate FindDoctorCommand

FindDoctorCommandParser --> MediConnectParser : d
deactivate FindDoctorCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindDoctorCommandParser -[hidden]-> MediConnectParser
destroy FindDoctorCommandParser

MediConnectParser --> LogicManager : d
deactivate MediConnectParser

LogicManager -> FindDoctorCommand : execute()
activate FindDoctorCommand

FindDoctorCommand -> Model : getFilteredDoctorList(predicate)
activate Model

Model --> FindDoctorCommand
deactivate Model

create CommandResult
FindDoctorCommand -> CommandResult
activate CommandResult

CommandResult --> FindDoctorCommand : result
deactivate CommandResult

FindDoctorCommand --> LogicManager : result
deactivate FindDoctorCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
