@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant "d:ListDoctorCommand" as ListDoctorCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list_d")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("list_d")
activate MediConnectParser

create ListDoctorCommand

MediConnectParser -> ListDoctorCommand
activate ListDoctorCommand

ListDoctorCommand --> MediConnectParser : d
deactivate ListDoctorCommand

MediConnectParser --> LogicManager : d
deactivate MediConnectParser

LogicManager -> ListDoctorCommand : execute()
activate ListDoctorCommand

ListDoctorCommand -> Model : updateFilteredDoctorList(\nPREDICATE_SHOW_ALL_DOCTORS)
activate Model

Model --> ListDoctorCommand
deactivate Model

create CommandResult
ListDoctorCommand -> CommandResult
activate CommandResult

CommandResult --> ListDoctorCommand : result
deactivate CommandResult

ListDoctorCommand --> LogicManager : result
deactivate ListDoctorCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
