@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediConnectParser" as MediConnectParser LOGIC_COLOR
participant ":ListAppointmentCommandParser" as ListAppointmentCommandParser LOGIC_COLOR
participant ":AppointmentFilterByNricPredicate" as AppointmentFilterByNricPredicate LOGIC_COLOR
participant "a:ListAppointmentCommand" as ListAppointmentCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list_a \npic\S9912343G dic\S0548254G")
activate LogicManager

LogicManager -> MediConnectParser : parseCommand("list_a \npic\S9912343G dic\S0548254G")
activate MediConnectParser

create ListAppointmentCommandParser
MediConnectParser -> ListAppointmentCommandParser
activate ListAppointmentCommandParser


ListAppointmentCommandParser --> MediConnectParser
deactivate ListAppointmentCommandParser

MediConnectParser -> ListAppointmentCommandParser : parse("pic\S9912343G \ndic\S0548254G")
activate ListAppointmentCommandParser

create AppointmentFilterByNricPredicate
ListAppointmentCommandParser -> AppointmentFilterByNricPredicate
activate AppointmentFilterByNricPredicate
AppointmentFilterByNricPredicate --> ListAppointmentCommandParser : predicate
deactivate AppointmentFilterByNricPredicate

create ListAppointmentCommand
ListAppointmentCommandParser -> ListAppointmentCommand :
activate ListAppointmentCommand




ListAppointmentCommand --> ListAppointmentCommandParser : a
deactivate ListAppointmentCommand

ListAppointmentCommandParser --> MediConnectParser : a
deactivate ListAppointmentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListAppointmentCommandParser -[hidden]-> MediConnectParser
destroy ListAppointmentCommandParser

MediConnectParser --> LogicManager : a
deactivate MediConnectParser

LogicManager -> ListAppointmentCommand : execute()
activate ListAppointmentCommand

ListAppointmentCommand -> Model : updateFilteredAppointmentList(predicate)
activate Model

Model --> ListAppointmentCommand
deactivate Model

create CommandResult
ListAppointmentCommand -> CommandResult
activate CommandResult

CommandResult --> ListAppointmentCommand : result
deactivate CommandResult

ListAppointmentCommand --> LogicManager : result
deactivate ListAppointmentCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
