@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes list command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([sort parameter present])
    if () then ([order parameter present])
        :Parser selects corresponding
        Comparator;
    else ([order paramter not present])
        :Parser selects Ascending Comparator;
    endif
else ([sort parameter not present])
    if () then ([order parameter not present])
        :Parser selects the default Comparator;
    else ([order parameter present])
        :Parser throws Exception;
    endif
endif

:Database sorts the list using the selected Comparator;
stop
@enduml
