@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "MediConnect Storage" #F4F6F6{
Class "<<interface>>\nDatabaseStorage" as DatabaseStorage
Class JsonDatabaseStorage
Class JsonSerializableDatabase
Class "{abstract}\nJsonAdaptedData" as JsonAdaptedData
Class "{abstract}\nJsonAdaptedPerson" as JsonAdaptedPerson
Class JsonAdaptedAppointment
Class JsonAdaptedDoctor
Class JsonAdaptedPatient
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" DatabaseStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> DatabaseStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonDatabaseStorage .up.|> DatabaseStorage
JsonDatabaseStorage ..> JsonSerializableDatabase
JsonSerializableDatabase --> "*" JsonAdaptedData
JsonAdaptedAppointment .up.|> JsonAdaptedData
JsonAdaptedPerson .up.|> JsonAdaptedData
JsonAdaptedPatient .up.|> JsonAdaptedPerson
JsonAdaptedDoctor .up.|> JsonAdaptedPerson
JsonAdaptedData --> "*" JsonAdaptedTag

@enduml
